import { NextResponse } from 'next/server';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { requireEventsAdmin } from '@/lib/events/authorization';
import { calculatePromoterPrice } from '@/lib/events/pricing';

function fail(e: unknown) { const m=e instanceof Error?e.message:'Request failed'; const status=m==='UNAUTHORIZED'?401:m==='FORBIDDEN'?403:400; return NextResponse.json({error:m},{status}); }
function cleanSlug(v:string){ return v.trim().toLowerCase().replace(/[^a-z0-9\u00C0-\u024F]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,120); }
function parseDate(v:string){ const d=new Date(v); if(Number.isNaN(d.getTime())) throw new Error('INVALID_DATE'); return d; }
function decimal(v:unknown){ const n=new Prisma.Decimal(String(v ?? '')); if(!n.isFinite() || n.lessThan(0)) throw new Error('INVALID_PRICE'); return n; }
export async function GET(){ try{ await requireEventsAdmin(); const [events,organizers,media]=await Promise.all([prisma.event.findMany({include:{organizer:true,coverMedia:true,gallery:{include:{media:true},orderBy:{sortOrder:'asc'}},_count:{select:{applications:true,promoterEvents:true}}},orderBy:{startsAt:'asc'}}),prisma.eventOrganizer.findMany({orderBy:{name:'asc'}}),prisma.media.findMany({orderBy:{createdAt:'desc'},take:200})]); return NextResponse.json({events,organizers,media}); }catch(e){return fail(e)} }
export async function POST(req:Request){ try{ await requireEventsAdmin(); const b=await req.json(); const name=String(b.name||'').trim(); const slug=cleanSlug(String(b.slug||name)); if(!name||!slug) throw new Error('NAME_AND_SLUG_REQUIRED'); const publicPrice=decimal(b.publicTicketPrice); const discount=decimal(b.promoterDiscountPercent); if(discount.greaterThan(100)) throw new Error('INVALID_DISCOUNT'); const promoterPrice=calculatePromoterPrice(publicPrice,discount); const event=await prisma.event.create({data:{name,slug,artist:String(b.artist||'').trim()||null,venue:String(b.venue||'').trim()||null,city:String(b.city||'').trim()||null,startsAt:parseDate(String(b.startsAt)),description:String(b.description||'').trim()||null,publicTicketPrice:publicPrice,promoterDiscountPercent:discount,totalInventory:Math.max(0,Number(b.totalInventory||0)),status:b.status||'DRAFT',internalNotes:String(b.internalNotes||'').trim()||null,organizerId:b.organizerId||null,coverMediaId:b.coverMediaId||null,gallery:{create:(Array.isArray(b.galleryMediaIds)?b.galleryMediaIds:[]).filter(Boolean).map((mediaId:string,i:number)=>({mediaId,sortOrder:i}))}}}); return NextResponse.json({event,promoterPrice:promoterPrice.toString()},{status:201}); }catch(e){return fail(e)} }
