import { Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { prisma } from '@/lib/prisma';

export async function getMailMetadata(folder:string){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT "uid", "starred", "clientId" FROM "MailMetadata" WHERE "folder"=${folder}`);}
export async function upsertMailMetadata(input:{folder:string;uid:number;read?:boolean;starred?:boolean;messageId?:string|null;clientId?:string|null;userId?:string|null}){const read=input.read??false, starred=input.starred??false;await prisma.$executeRaw(Prisma.sql`INSERT INTO "MailMetadata" ("id","folder","uid","read","starred","messageId","clientId","updatedAt","userId") VALUES (${randomUUID()},${input.folder},${input.uid},${read},${starred},${input.messageId??null},${input.clientId??null},CURRENT_TIMESTAMP,${input.userId??null}) ON CONFLICT ("folder","uid") DO UPDATE SET "read"=${read},"starred"=${starred},"messageId"=${input.messageId??null},"clientId"=COALESCE(${input.clientId??null},"MailMetadata"."clientId"),"updatedAt"=CURRENT_TIMESTAMP`);}
export async function moveMailMetadata(fromFolder:string,uid:number,toFolder:string){await prisma.$executeRaw(Prisma.sql`UPDATE "MailMetadata" SET "folder"=${toFolder},"updatedAt"=CURRENT_TIMESTAMP WHERE "folder"=${fromFolder} AND "uid"=${uid}`);}
export async function listDrafts(userId:string){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT d."id",d."to",d."cc",d."bcc",d."subject",d."body",d."clientId",d."createdAt",d."updatedAt",COALESCE((SELECT json_agg(json_build_object('id',a."id",'filename',a."filename",'mimeType',a."mimeType",'sizeBytes',a."sizeBytes") ORDER BY a."createdAt") FROM "MailDraftAttachment" a WHERE a."draftId"=d."id"),'[]'::json) AS "attachments" FROM "MailDraft" d WHERE d."createdById"=${userId} ORDER BY d."updatedAt" DESC`);}
export async function getDraft(userId:string,id:string){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT d."id",d."to",d."cc",d."bcc",d."subject",d."body",d."clientId",d."createdAt",d."updatedAt",COALESCE((SELECT json_agg(json_build_object('id',a."id",'filename',a."filename",'mimeType',a."mimeType",'sizeBytes',a."sizeBytes") ORDER BY a."createdAt") FROM "MailDraftAttachment" a WHERE a."draftId"=d."id"),'[]'::json) AS "attachments" FROM "MailDraft" d WHERE d."id"=${id} AND d."createdById"=${userId} LIMIT 1`);return rows[0]||null;}
export async function createDraft(userId:string,data:{to:string;cc:string|null;bcc:string|null;subject:string|null;body:string;clientId:string|null}){const id=randomUUID();await prisma.$executeRaw(Prisma.sql`INSERT INTO "MailDraft" ("id","createdById","clientId","to","cc","bcc","subject","body","createdAt","updatedAt") VALUES (${id},${userId},${data.clientId},${data.to},${data.cc},${data.bcc},${data.subject},${data.body},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`);return id;}
export async function updateDraft(userId:string,id:string,data:{to:string;cc:string|null;bcc:string|null;subject:string|null;body:string;clientId:string|null}){const result=await prisma.$executeRaw(Prisma.sql`UPDATE "MailDraft" SET "clientId"=${data.clientId},"to"=${data.to},"cc"=${data.cc},"bcc"=${data.bcc},"subject"=${data.subject},"body"=${data.body},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${id} AND "createdById"=${userId}`);if(!result)throw new Error('DRAFT_NOT_FOUND');}
export async function deleteDraft(userId:string,id:string){const result=await prisma.$executeRaw(Prisma.sql`DELETE FROM "MailDraft" WHERE "id"=${id} AND "createdById"=${userId}`);if(!result)throw new Error('DRAFT_NOT_FOUND');}
export async function addDraftAttachment(draftId:string,a:{filename:string;mimeType:string;sizeBytes:number;data:Buffer}){await prisma.$executeRaw(Prisma.sql`INSERT INTO "MailDraftAttachment" ("id","draftId","filename","mimeType","sizeBytes","data","createdAt") VALUES (${randomUUID()},${draftId},${a.filename},${a.mimeType},${a.sizeBytes},${a.data},CURRENT_TIMESTAMP)`);}
export async function getDraftAttachments(userId:string,draftId:string){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT a."filename",a."mimeType",a."sizeBytes",a."data" FROM "MailDraftAttachment" a INNER JOIN "MailDraft" d ON d."id"=a."draftId" WHERE d."id"=${draftId} AND d."createdById"=${userId}`);}
export async function getDraftAttachment(userId:string,id:string){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT a."filename",a."mimeType",a."data" FROM "MailDraftAttachment" a INNER JOIN "MailDraft" d ON d."id"=a."draftId" WHERE a."id"=${id} AND d."createdById"=${userId} LIMIT 1`);return rows[0]||null;}
export async function findClientByEmail(email:string){const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT "id","firstName","lastName" FROM "Client" WHERE lower("email")=lower(${email}) LIMIT 1`);return rows[0]||null;}
export async function recordEmailCommunication(data:{messageId:string;clientId:string;direction:'INBOUND'|'OUTBOUND';subject:string|null;fromAddress:string;toAddress:string;sentAt:Date}){await prisma.$executeRaw(Prisma.sql`INSERT INTO "EmailCommunication" ("id","messageId","clientId","direction","subject","fromAddress","toAddress","sentAt","createdAt") VALUES (${randomUUID()},${data.messageId},${data.clientId},${data.direction}::"EmailDirection",${data.subject},${data.fromAddress},${data.toAddress},${data.sentAt},CURRENT_TIMESTAMP) ON CONFLICT ("messageId") DO UPDATE SET "clientId"=${data.clientId},"subject"=${data.subject},"sentAt"=${data.sentAt}`);}
export async function getClientsWithEmail(){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT "id","firstName","lastName","email","company" FROM "Client" WHERE "email" IS NOT NULL ORDER BY "firstName" ASC`);}
export async function getClientCommunications(id:string){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT "id","messageId","direction","subject","fromAddress","toAddress","sentAt","createdAt" FROM "EmailCommunication" WHERE "clientId"=${id} ORDER BY "sentAt" DESC LIMIT 50`);}
