'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ArrowLeft,CalendarDays,Ticket,TrendingUp,Wallet } from 'lucide-react';
const money=(v:any)=>`${new Intl.NumberFormat('az-AZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₼`;
const dt=(v:any)=>new Intl.DateTimeFormat('az-AZ',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
export default function PromoterEventWorkspace({eventId}:{eventId:string}){
 const[d,setD]=useState<any>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch(`/api/promoter/events/${eventId}`,{cache:'no-store'});const x=await r.json();if(!r.ok)throw new Error(x.error);setD(x);setError('')}catch(e:any){setError(e.message||'Məlumat yüklənmədi')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventId]);
 async function sell(ticketId:string,promoterPrice:any){const raw=window.prompt(`Müştəriyə faktiki satış qiyməti (promoter qiyməti ${money(promoterPrice)}):`);if(raw===null)return;const price=Number(raw);if(!Number.isFinite(price)||price<0){alert('Düzgün satış qiyməti daxil edin.');return}const customer=window.prompt('Müştəri adı (istəyə bağlı):')||'';const r=await fetch('/api/promoter/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticketId,actualSalePrice:price,customerName:customer})});const x=await r.json();if(!r.ok){alert(x.error);return}load()}
 if(loading&&!d)return <main className="promoterEventWorkspace"><div className="promoterWorkspaceLoading">Yüklənir…</div></main>;
 if(error&&!d)return <main className="promoterEventWorkspace"><div className="promoterWorkspaceError">{error}</div></main>;
 const r=d.relation,e=r.event,f=d.finance;
 return <main className="promoterEventWorkspace"><div className="promoterWorkspaceShell"><Link href="/promoter" className="promoterWorkspaceBack"><ArrowLeft size={15}/> Promoter paneli</Link><header className="promoterWorkspaceHeader"><div className="promoterWorkspaceIdentity">{e.coverMedia?.url?<img src={e.coverMedia.url} alt=""/>:<div>NE</div>}<section><small>MY EVENT WORKSPACE</small><h1>{e.name}</h1><p>{e.artist||'Artist'} · {[e.city,e.venue].filter(Boolean).join(' · ')}</p><span><CalendarDays size={13}/> {dt(e.startsAt)}</span></section></div><div className="promoterWorkspacePrice"><small>SƏNİN PROMOTER QİYMƏTİN</small><strong>{money(r.promoterPrice)}</strong><span>{Number(r.promoterDiscountPercent).toFixed(2)}% endirim</span></div></header><section className="promoterWorkspaceStats"><Stat icon={<Ticket size={17}/>} label="Allocation" value={r.allocation}/><Stat icon={<TrendingUp size={17}/>} label="Satılıb" value={r.soldQuantity}/><Stat icon={<Ticket size={17}/>} label="Qalıb" value={r.remainingQuantity}/><Stat icon={<Wallet size={17}/>} label="Qalıq borc" value={money(f.debt)}/></section><section className="promoterWorkspacePanel"><div className="promoterWorkspaceTitle"><div><small>TICKETS</small><h2>Biletlər</h2></div><span>Public qiymət: {money(e.publicTicketPrice)}</span></div><div className="promoterWorkspaceTickets">{d.tickets.map((a:any)=><article key={a.id}><div><small>{a.ticket.status}</small><strong>{a.ticket.ticketNumber}</strong></div><div>{a.ticket.status==='ALLOCATED'?<button onClick={()=>sell(a.ticket.id,a.promoterPrice)}>Satış kimi qeyd et</button>:<span>{a.ticket.status==='SOLD'?'Satılıb':'Qaytarılıb'}</span>}</div></article>)}</div></section><section className="promoterWorkspaceGrid"><section className="promoterWorkspacePanel"><div className="promoterWorkspaceTitle"><div><small>SALES</small><h2>Satışlar</h2></div></div>{d.sales.length===0?<p className="promoterWorkspaceMuted">Hələ satış yoxdur.</p>:<div className="promoterWorkspaceSales">{d.sales.map((s:any)=><article key={s.id}><div><b>{s.ticket.ticketNumber}</b><span>{dt(s.soldAt)}</span></div><strong>{money(s.actualSalePrice)}</strong><em>+{money(s.margin)}</em></article>)}</div>}</section><section className="promoterWorkspacePanel"><div className="promoterWorkspaceTitle"><div><small>FINANCE</small><h2>Maliyyə</h2></div></div><div className="promoterFinanceRows"><div><span>Satış gəliri</span><b>{money(f.revenue)}</b></div><div><span>Margin</span><b>{money(f.margin)}</b></div><div><span>New Era borcu</span><b>{money(f.debit)}</b></div><div><span>Ödənilib</span><b>{money(f.credit)}</b></div><div><span>Qalıq</span><b>{money(f.debt)}</b></div></div></section></section></div></main>;
}
function Stat({icon,label,value}:{icon:any,label:string,value:any}){return <div className="promoterWorkspaceStat"><div>{icon}</div><small>{label}</small><strong>{value}</strong></div>}
