import Link from 'next/link';
import { CalendarDays, MapPin, ArrowUpRight, Ticket, Sparkles } from 'lucide-react';
import { prisma } from '@/lib/prisma';

const date=(v:Date)=>new Intl.DateTimeFormat('az-AZ',{day:'2-digit',month:'long',year:'numeric'}).format(v);
const time=(v:Date)=>new Intl.DateTimeFormat('az-AZ',{hour:'2-digit',minute:'2-digit'}).format(v);
const money=(v:unknown)=>`${new Intl.NumberFormat('az-AZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v))} AZN`;
const status=(s:string)=>s==='APPLICATION_OPEN'?'Müraciət açıqdır':s==='SOLD_OUT'?'Biletlər bitib':'Aktiv';

export default async function EventsPage(){
 const events=await prisma.event.findMany({where:{status:{in:['APPLICATION_OPEN','ACTIVE','SOLD_OUT']}},include:{coverMedia:true},orderBy:{startsAt:'asc'}});
 const featured=events[0]; const rest=featured?events.slice(1):[];
 return <main className="eventsPublicPage">
  <section className="eventsPublicHero"><div className="eventsPublicHeroGlow"/><div className="eventsPublicContainer"><Link href="/" className="eventsBackLink">← New Era</Link><div className="eventsEyebrow">NEW ERA · EVENTS</div><h1>Unudulmaz gecələr.<br/><span>Güclü səhnələr.</span></h1><p>New Era tərəfindən seçilmiş tədbirləri kəşf et və uyğun tədbirlər üçün promoter kimi əməkdaşlığa müraciət et.</p><div className="eventsHeroActions"><a href="#upcoming" className="eventPrimaryCta">Tədbirlərə bax <ArrowUpRight size={15}/></a><span><Sparkles size={14}/> Yeni tədbirlər mütəmadi əlavə olunur</span></div></div></section>
  {featured&&<section className="eventsPublicContainer eventsFeaturedSection"><div className="eventsSectionLabel"><span>FEATURED EVENT</span><i/></div><article className="eventsFeaturedCard"><Link href={`/events/${featured.slug}`} className="eventsFeaturedMedia">{featured.coverMedia?.url?<img src={featured.coverMedia.url} alt={featured.coverMedia.alt||featured.name}/>:<div className="eventCardImageFallback">NEW ERA</div>}<span className="eventStatus">{status(featured.status)}</span></Link><div className="eventsFeaturedContent"><div className="eventsEyebrow">{featured.artist||'NEW ERA EVENTS'}</div><h2>{featured.name}</h2><div className="eventsFeaturedFacts"><span><CalendarDays size={15}/>{date(featured.startsAt)} · {time(featured.startsAt)}</span><span><MapPin size={15}/>{[featured.venue,featured.city].filter(Boolean).join(' · ')||'Məkan müəyyən ediləcək'}</span></div>{featured.description&&<p>{featured.description}</p>}<div className="eventsFeaturedBottom"><div><small>PUBLIC TICKET PRICE</small><strong>{money(featured.publicTicketPrice)}</strong></div><Link href={`/events/${featured.slug}`} className="eventPrimaryCta">Tədbirə bax <ArrowUpRight size={15}/></Link></div></div></article></section>}
  <section id="upcoming" className="eventsPublicContainer eventsGridSection"><div className="eventsSectionLabel"><span>UPCOMING EVENTS</span><i/></div>{events.length===0?<div className="eventsEmptyState"><Ticket size={22}/><strong>Hazırda açıq tədbir yoxdur.</strong><span>Yeni tədbirlər əlavə edildikdə burada görünəcək.</span></div>:<div className="eventsGrid">{rest.map(e=><article className="eventCard" key={e.id}><Link href={`/events/${e.slug}`} className="eventCardImage">{e.coverMedia?.url?<img src={e.coverMedia.url} alt={e.coverMedia.alt||e.name}/>:<div className="eventCardImageFallback">NEW ERA</div>}<span className={`eventStatus eventStatus-${e.status.toLowerCase()}`}>{status(e.status)}</span></Link><div className="eventCardBody"><div className="eventCardMeta">{e.artist||'EVENT'}</div><Link href={`/events/${e.slug}`} className="eventCardTitle">{e.name}</Link><div className="eventCardInfo"><CalendarDays size={14}/>{date(e.startsAt)} · {time(e.startsAt)}</div><div className="eventCardInfo"><MapPin size={14}/>{[e.venue,e.city].filter(Boolean).join(', ')||'Məkan müəyyən ediləcək'}</div><div className="eventCardFooter"><div><small>PUBLIC TICKET PRICE</small><strong>{money(e.publicTicketPrice)}</strong></div><Link href={`/events/${e.slug}`} className="eventCardArrow">Ətraflı →</Link></div></div></article>)}</div>}{events.length===1&&<div className="eventsOnlyFeaturedNote">Hazırda ən yaxın tədbir yuxarıda göstərilir. Yeni tədbirlər əlavə olunduqca bu bölmədə görünəcək.</div>}</section>
  <section className="eventsPublicContainer eventsPromoterCtaSection"><div><div className="eventsEyebrow">PROMOTER PROGRAM</div><h2>Tədbirlərdə New Era ilə əməkdaşlıq et.</h2><p>Uyğun tədbiri seç, promoter müraciəti göndər və təsdiqdən sonra sənə ayrılmış biletlərlə satışa başla.</p></div><Link href={featured&&featured.status==='APPLICATION_OPEN'?`/events/${featured.slug}/apply`:'/events'} className="eventPrimaryCta">Promoter kimi əməkdaşlıq et <ArrowUpRight size={15}/></Link></section>
 </main>;
}
