'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Building2, UserRound } from 'lucide-react';
const jobs=['CEO / Təsisçi','Marketinq meneceri','Brend meneceri','SMM meneceri','Kreativ direktor','HR meneceri','Satış meneceri','Məhsul meneceri','Digər'];
const industries=['Reklam və kreativ','Texnologiya','Pərakəndə və e-ticarət','Səhiyyə','Maliyyə','Daşınmaz əmlak','Təhsil','Qonaqpərvərlik','Digər'];
const sizes=['1–10','11–50','51–200','201–500','500+'];
export default function Register(){
 const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',password:'',company:'',website:'',jobTitle:'',industry:'',size:'',country:'Azerbaijan'}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,companySize:form.size})});const data=await res.json();if(!res.ok){setError(data.error||'Hesab yaratmaq mümkün olmadı.');return;}window.location.href=`/verify?identifier=${encodeURIComponent(data.identifier)}&target=${encodeURIComponent(data.target||'')}&flow=client`;}catch{setError('Hazırda New Era ilə əlaqə yaratmaq mümkün olmadı.');}finally{setLoading(false);}}
 return <main className="authPage"><div className="authGlow"/><div className="authCard authWide"><Link className="authBrand" href="/"><img src="/new-era-logo-header.png" alt="New Era"/></Link><div className="eyebrow">NEW ERA-A QOŞULUN</div><h1><span>müştəri hesabınızı</span> yaradın.</h1><p className="authIntro">Şirkət profiliniz bütün brief-ləri, layihələri və New Era yazışmalarını vahid iş məkanında birləşdirir.</p><form onSubmit={submit} className="authForm"><div className="authSectionTitle"><UserRound size={16}/><span>Şəxsi məlumatlar</span></div><div className="formSplit"><label>Ad<input required value={form.firstName} onChange={e=>update('firstName',e.target.value)} placeholder="Adınız"/></label><label>Soyad<input required value={form.lastName} onChange={e=>update('lastName',e.target.value)} placeholder="Soyadınız"/></label></div><div className="formSplit"><label>İş e-poçtu<input required type="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="name@company.com"/></label><label>Telefon<input required value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="+994 ..."/></label></div><label>Şifrə<input required minLength={8} type="password" value={form.password} onChange={e=>update('password',e.target.value)} placeholder="Ən azı 8 simvol"/></label><div className="authSectionTitle"><Building2 size={16}/><span>Şirkət məlumatları</span></div><label>Şirkət adı<input required value={form.company} onChange={e=>update('company',e.target.value)} placeholder="Şirkətiniz"/></label><div className="formSplit"><label>Vəzifəniz<select required value={form.jobTitle} onChange={e=>update('jobTitle',e.target.value)}><option value="">Vəzifənizi seçin</option>{jobs.map(x=><option key={x}>{x}</option>)}</select></label><label>Sahə<select required value={form.industry} onChange={e=>update('industry',e.target.value)}><option value="">Sahəni seçin</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="formSplit"><label>Şirkət ölçüsü<select required value={form.size} onChange={e=>update('size',e.target.value)}><option value="">Ölçünü seçin</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Vebsayt <span className="istəyə görə">istəyə görə</span><input value={form.website} onChange={e=>update('website',e.target.value)} placeholder="company.com"/></label></div><label>Ölkə<input value={form.country} onChange={e=>update('country',e.target.value)} placeholder="Azərbaycan"/></label>{error&&<div className="authError">{error}</div>}<button disabled={loading} className="primary authSubmit" type="submit">{loading?'Hesab yaradılır…':'Müştəri hesabı yarat'} {!loading&&<ArrowRight size={16}/>}</button><div className="authFoot">Artıq hesabınız var? <Link href="/login">Daxil olun</Link></div></form><div className="authPrivacy">New Era mütəxəssislərin əlaqə məlumatlarını gizli saxlayır və müştəri ünsiyyətini platforma daxilində idarə edir.</div></div></main>;
}
