CREATE TYPE "FinanceTransactionType" AS ENUM ('INCOME','EXPENSE','TRANSFER');
CREATE TYPE "FinanceTransactionStatus" AS ENUM ('POSTED','VOID','REVERSED');
CREATE TYPE "FinanceAccountType" AS ENUM ('BANK','CASH','CARD','OTHER');
CREATE TYPE "FinanceAccountStatus" AS ENUM ('ACTIVE','INACTIVE');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT','SENT','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED');
CREATE TYPE "PaymentMethod" AS ENUM ('BANK_TRANSFER','CASH','CARD','ONLINE_PAYMENT','OTHER');
CREATE TYPE "PayableStatus" AS ENUM ('OPEN','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED');
CREATE TYPE "VendorStatus" AS ENUM ('ACTIVE','INACTIVE');
CREATE TABLE "FinanceAccount" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"type" "FinanceAccountType" NOT NULL DEFAULT 'BANK',"openingBalance" DECIMAL(14,2) NOT NULL DEFAULT 0,"currency" TEXT NOT NULL DEFAULT 'AZN',"status" "FinanceAccountStatus" NOT NULL DEFAULT 'ACTIVE',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FinanceAccount_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Vendor" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"company" TEXT,"phone" TEXT,"email" TEXT,"taxId" TEXT,"address" TEXT,"notes" TEXT,"status" "VendorStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Vendor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL,"number" TEXT NOT NULL,"clientId" TEXT NOT NULL,"projectId" TEXT,"issueDate" TIMESTAMP(3) NOT NULL,"dueDate" TIMESTAMP(3) NOT NULL,"subtotal" DECIMAL(14,2) NOT NULL,"tax" DECIMAL(14,2) NOT NULL DEFAULT 0,"discount" DECIMAL(14,2) NOT NULL DEFAULT 0,"total" DECIMAL(14,2) NOT NULL,"paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"currency" TEXT NOT NULL DEFAULT 'AZN',"status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',"notes" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number");
CREATE TABLE "InvoiceItem" ("id" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"serviceName" TEXT,"description" TEXT NOT NULL,"quantity" DECIMAL(12,2) NOT NULL DEFAULT 1,"unitPrice" DECIMAL(14,2) NOT NULL,"discount" DECIMAL(14,2) NOT NULL DEFAULT 0,"total" DECIMAL(14,2) NOT NULL,CONSTRAINT "InvoiceItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FinancePayment" ("id" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"date" TIMESTAMP(3) NOT NULL,"method" "PaymentMethod" NOT NULL,"accountId" TEXT,"reference" TEXT,"notes" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"clientId" TEXT,CONSTRAINT "FinancePayment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FinancePayable" ("id" TEXT NOT NULL,"vendorId" TEXT NOT NULL,"description" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"dueDate" TIMESTAMP(3) NOT NULL,"paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,"status" "PayableStatus" NOT NULL DEFAULT 'OPEN',"projectId" TEXT,"category" TEXT NOT NULL,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FinancePayable_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FinanceTransaction" ("id" TEXT NOT NULL,"date" TIMESTAMP(3) NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"type" "FinanceTransactionType" NOT NULL,"status" "FinanceTransactionStatus" NOT NULL DEFAULT 'POSTED',"category" TEXT NOT NULL,"description" TEXT NOT NULL,"accountId" TEXT,"toAccountId" TEXT,"clientId" TEXT,"vendorId" TEXT,"projectId" TEXT,"invoiceId" TEXT,"paymentMethod" "PaymentMethod","reference" TEXT,"notes" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FinanceTransaction_pkey" PRIMARY KEY ("id"));
CREATE INDEX "FinanceAccount_status_idx" ON "FinanceAccount"("status");
CREATE INDEX "Vendor_name_idx" ON "Vendor"("name");
CREATE INDEX "Vendor_status_idx" ON "Vendor"("status");
CREATE INDEX "Invoice_clientId_dueDate_idx" ON "Invoice"("clientId","dueDate");
CREATE INDEX "Invoice_projectId_idx" ON "Invoice"("projectId");
CREATE INDEX "Invoice_status_dueDate_idx" ON "Invoice"("status","dueDate");
CREATE INDEX "InvoiceItem_invoiceId_idx" ON "InvoiceItem"("invoiceId");
CREATE INDEX "FinancePayment_invoiceId_date_idx" ON "FinancePayment"("invoiceId","date");
CREATE INDEX "FinancePayment_clientId_idx" ON "FinancePayment"("clientId");
CREATE INDEX "FinancePayable_vendorId_dueDate_idx" ON "FinancePayable"("vendorId","dueDate");
CREATE INDEX "FinancePayable_status_dueDate_idx" ON "FinancePayable"("status","dueDate");
CREATE INDEX "FinancePayable_projectId_idx" ON "FinancePayable"("projectId");
CREATE INDEX "FinanceTransaction_date_type_status_idx" ON "FinanceTransaction"("date","type","status");
CREATE INDEX "FinanceTransaction_accountId_date_idx" ON "FinanceTransaction"("accountId","date");
CREATE INDEX "FinanceTransaction_toAccountId_date_idx" ON "FinanceTransaction"("toAccountId","date");
CREATE INDEX "FinanceTransaction_clientId_idx" ON "FinanceTransaction"("clientId");
CREATE INDEX "FinanceTransaction_vendorId_idx" ON "FinanceTransaction"("vendorId");
CREATE INDEX "FinanceTransaction_projectId_idx" ON "FinanceTransaction"("projectId");
CREATE INDEX "FinanceTransaction_invoiceId_idx" ON "FinanceTransaction"("invoiceId");
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InvoiceItem" ADD CONSTRAINT "InvoiceItem_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FinancePayment" ADD CONSTRAINT "FinancePayment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FinancePayment" ADD CONSTRAINT "FinancePayment_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinancePayment" ADD CONSTRAINT "FinancePayment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinancePayable" ADD CONSTRAINT "FinancePayable_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FinancePayable" ADD CONSTRAINT "FinancePayable_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "FinanceAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_toAccountId_fkey" FOREIGN KEY ("toAccountId") REFERENCES "FinanceAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FinanceTransaction" ADD CONSTRAINT "FinanceTransaction_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
