'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, ExternalLink, RefreshCw, Ticket, Users, Wallet, TrendingUp, ClipboardList } from 'lucide-react';

const money=(v:any)=>`${new Intl.NumberFormat('az-AZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))} ₼`;
const dt=(v:any)=>new Intl.DateTimeFormat('az-AZ',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const statusLabel=(s:string)=>({DRAFT:'Hazırlanır',APPLICATION_OPEN:'Müraciət açıq',ACTIVE:'Aktiv',SOLD_OUT:'Sold out',COMPLETED:'Tamamlanıb',CANCELLED:'Ləğv edilib'} as Record<string,string>)[s]||s;

type Tab='overview'|'promoters'|'sales'|'finance'|'applications'|'audit';
export default function EventOperationsClient({eventId}:{eventId:string}){
 const [data,setData]=useState<any>(null); const [tab,setTab]=useState<Tab>('overview'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function load(){setLoading(true);try{const r=await fetch(`/api/admin/events/${eventId}/operations`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e:any){setError(e.message||'Məlumat yüklənmədi')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventId]);
 if(loading&&!data)return <main className="eventOpsPage"><div className="eventOpsLoading">Yüklənir…</div></main>;
 if(error&&!data)return <main className="eventOpsPage"><div className="eventOpsError">{error}</div></main>;
 const e=data.event, inv=data.inventory||{}, f=data.financial||{};
 return <main className="eventOpsPage"><div className="eventOpsShell">
   <Link href="/admin/events" className="eventOpsBack"><ArrowLeft size={15}/> Events</Link>
   <header className="eventOpsHeader"><div className="eventOpsIdentity">{e.coverMedia?.url?<img src={e.coverMedia.url} alt=""/>:<div>NE</div>}<section><span className="eventOpsEyebrow">EVENT OPERATIONS</span><h1>{e.name}</h1><p>{e.artist||'Artist qeyd edilməyib'} · {[e.city,e.venue].filter(Boolean).join(' · ')||'Məkan qeyd edilməyib'}</p><small>{dt(e.startsAt)} · {statusLabel(e.status)}</small></section></div><div className="eventOpsActions"><Link href={`/events/${e.slug}`} target="_blank"><ExternalLink size={14}/> Public Preview</Link><button onClick={load}><RefreshCw size={14}/> Yenilə</button></div></header>
   <section className="eventOpsStats"><Stat icon={<Users size={18}/>} label="Promoterlər" value={e.promoterEvents.length}/><Stat icon={<Ticket size={18}/>} label="Inventory" value={e.totalInventory}/><Stat icon={<TrendingUp size={18}/>} label="Satılıb" value={inv.SOLD||0}/><Stat icon={<Wallet size={18}/>} label="Qalıq borc" value={money(f.outstanding)}/></section>
   <nav className="eventOpsTabs">{([['overview','Overview'],['promoters','Promoterlər'],['sales','Satışlar'],['finance','Maliyyə'],['applications','Müraciətlər'],['audit','Audit']] as [Tab,string][]).map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
   {tab==='overview'&&<Overview e={e} inv={inv} f={f}/>} {tab==='promoters'&&<Promoters rows={e.promoterEvents}/>} {tab==='sales'&&<Sales rows={data.sales}/>} {tab==='finance'&&<Finance f={f} rows={data.payments}/>} {tab==='applications'&&<Applications rows={data.applications}/>} {tab==='audit'&&<Audit rows={data.audit}/>} 
 </div></main>
}
function Stat({icon,label,value}:{icon:any,label:string,value:any}){return <div className="eventOpsStat"><div>{icon}</div><small>{label}</small><strong>{value}</strong></div>}
function Overview({e,inv,f}:{e:any,inv:any,f:any}){return <div className="eventOpsGrid"><section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>EVENT SUMMARY</small><h2>Əsas göstəricilər</h2></div></div><div className="eventOpsMetricGrid"><Metric label="Public qiymət" value={money(e.publicTicketPrice)}/><Metric label="Promoter qiyməti" value={money(e.promoterPrice)}/><Metric label="Endirim" value={`${Number(e.promoterDiscountPercent).toFixed(2)}%`}/><Metric label="Allocation" value={inv.ALLOCATED||0}/><Metric label="Available" value={inv.AVAILABLE||0}/><Metric label="Returned" value={inv.RETURNED||0}/><Metric label="Cancelled" value={inv.CANCELLED||0}/><Metric label="Sold" value={inv.SOLD||0}/></div></section><section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>FINANCE</small><h2>Maliyyə xülasəsi</h2></div></div><div className="eventOpsFinanceRows"><Metric label="Müştəri satışları" value={money(f.revenue)}/><Metric label="Promoter cost" value={money(f.promoterCost)}/><Metric label="Margin" value={money(f.margin)}/><Metric label="Alınmalı" value={money(f.receivable)}/><Metric label="Toplanan" value={money(f.collected)}/><Metric label="Qalıq borc" value={money(f.outstanding)}/></div></section></div>}
function Metric({label,value}:{label:string,value:any}){return <div className="eventOpsMetric"><small>{label}</small><strong>{value}</strong></div>}
function Promoters({rows}:any){return <section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>PROMOTER PERFORMANCE</small><h2>Tədbir üzrə promoterlər</h2></div></div><div className="eventOpsTableWrap"><table><thead><tr><th>Promoter</th><th>Status</th><th>Allocation</th><th>Satılıb</th><th>Qalıb</th><th>Promoter qiyməti</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.promoterId}><td><b>{r.promoter.firstName} {r.promoter.lastName}</b><small>{r.promoter.email||r.promoter.phone||''}</small></td><td>{r.status}</td><td>{r.allocation}</td><td>{r.soldQuantity}</td><td>{r.remainingQuantity}</td><td>{money(r.promoterPrice)}</td></tr>)}</tbody></table></div></section>}
function Sales({rows}:any){return <section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>ACTUAL SALES</small><h2>Satış tarixçəsi</h2></div></div><div className="eventOpsTableWrap"><table><thead><tr><th>Tarix</th><th>Promoter</th><th>Ticket</th><th>Müştəri</th><th>Promoter</th><th>Satış</th><th>Margin</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{dt(r.soldAt)}</td><td>{r.promoter.firstName} {r.promoter.lastName}</td><td>{r.ticket.ticketNumber}</td><td>{r.customerName||'—'}</td><td>{money(r.promoterPrice)}</td><td>{money(r.actualSalePrice)}</td><td>{money(r.margin)}</td></tr>)}</tbody></table></div></section>}
function Finance({f,rows}:any){return <section className="eventOpsPanel"><div className="eventOpsMetricGrid"><Metric label="Alınmalı" value={money(f.receivable)}/><Metric label="Toplanan" value={money(f.collected)}/><Metric label="Qalıq" value={money(f.outstanding)}/></div><div className="eventOpsPanelTitle"><div><small>PAYMENTS</small><h2>Ödənişlər</h2></div></div><div className="eventOpsTableWrap"><table><thead><tr><th>Tarix</th><th>Promoter</th><th>Məbləğ</th><th>Metod</th><th>Reference</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{dt(r.paidAt)}</td><td>{r.promoter.firstName} {r.promoter.lastName}</td><td>{money(r.amount)}</td><td>{r.method}</td><td>{r.reference||'—'}</td></tr>)}</tbody></table></div></section>}
function Applications({rows}:any){return <section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>APPLICATIONS</small><h2>Promoter müraciətləri</h2></div></div><div className="eventOpsTableWrap"><table><thead><tr><th>Promoter</th><th>Əlaqə</th><th>Status</th><th>Müraciət</th><th>Review</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><b>{r.promoter.firstName} {r.promoter.lastName}</b></td><td>{r.promoter.email||r.promoter.phone||'—'}</td><td>{r.status}</td><td>{dt(r.createdAt)}</td><td>{r.reviewedAt?dt(r.reviewedAt):'—'}</td></tr>)}</tbody></table></div></section>}
function Audit({rows}:any){return <section className="eventOpsPanel"><div className="eventOpsPanelTitle"><div><small>AUDIT TRAIL</small><h2>Əməliyyat tarixçəsi</h2></div></div><div className="eventOpsTimeline">{rows.map((r:any)=><article key={r.id}><span>{dt(r.createdAt)}</span><strong>{r.action}</strong><p>{r.actor?.email||'System'} {r.promoter?`· ${r.promoter.firstName} ${r.promoter.lastName}`:''}</p></article>)}</div></section>}
