'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ShieldCheck } from 'lucide-react';
export default function VerifyPage(){
 const [identifier,setIdentifier]=useState(''); const [target,setTarget]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false); const [resending,setResending]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setIdentifier(q.get('identifier')||'');setTarget(q.get('target')||q.get('identifier')||'');},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');setNotice('');setLoading(true);try{const res=await fetch('/api/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier,code})});const data=await res.json();if(!res.ok){setError(data.error||'The code is invalid or expired.');return;}if(data.user?.client)localStorage.setItem('new-era-client-session',JSON.stringify(data.user.client));window.location.href='/account';}catch{setError('Unable to connect to New Era right now.');}finally{setLoading(false);}}
 async function resend(){setError('');setNotice('');setResending(true);try{const res=await fetch('/api/auth/resend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier})});const data=await res.json();if(!res.ok){setError(data.error||'Unable to resend the code.');return;}setTarget(data.target||target);setNotice('A new verification code has been sent.');}catch{setError('Unable to connect to New Era right now.');}finally{setResending(false);}}
 return <main className="authPage"><div className="authGlow"/><div className="authCard"><Link className="authBrand" href="/"><img src="/new-era-logo.svg" alt="New Era"/></Link><div className="eyebrow">VERIFY YOUR ACCOUNT</div><h1>One more <span>step.</span></h1><p className="authIntro">Enter the 6-digit code we sent to <strong>{target || 'your contact'}</strong>. This confirms that the email address or phone number actually belongs to you.</p><form onSubmit={submit} className="authForm"><label>Verification code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456" autoComplete="one-time-code"/></label>{error&&<div className="authError">{error}</div>}{notice&&<div className="authNotice">{notice}</div>}<button disabled={loading} className="primary authSubmit" type="submit">{loading?'Verifying…':'Verify account'} {!loading&&<ArrowRight size={16}/>}</button><button disabled={resending} type="button" className="secondary authResend" onClick={resend}>{resending?'Sending…':'Send a new code'}</button></form><div className="verificationHint"><ShieldCheck size={17}/><span>Verification codes expire after 10 minutes. New Era never stores your verification code in plain text.</span></div><div className="authFoot">Wrong contact? <Link href="/register">Create the account again</Link></div></div></main>;
}
