'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, ArrowLeft, ArrowRight, Asterisk, ChevronDown, Download, File, Forward, Inbox, Mail as MailIcon, Menu, Paperclip, PenLine, RefreshCw, Reply, Search, Send, Star, Trash2, X, Clock3 } from 'lucide-react';

type Address={name?:string|null;address:string};
type Message={uid:number|string;draftId?:string;folder?:string;from:Address[];to:Address[];cc:Address[];subject:string;date:string;unread:boolean;starred:boolean;flags?:string[];size?:number;preview?:string;messageId?:string|null};
type Detail=Message & {html:string;text:string;attachments:{filename:string;mimeType:string;size:number}[];clientId?:string|null;clientName?:string|null;inReplyTo?:string;references?:string};
type Client={id:string;firstName:string;lastName:string;email:string|null;company?:string|null};
type Draft={id:string;to:string;cc:string|null;bcc:string|null;subject:string|null;body:string;clientId:string|null;attachments:{id:string;filename:string;mimeType:string;sizeBytes:number}[]};

const folders=[['inbox','Gələnlər',Inbox],['sent','Göndərilənlər',Send],['drafts','Qaralamalar',PenLine],['starred','Seçilmişlər',Star],['trash','Zibil qutusu',Trash2]] as const;
const fmtDate=(d:string)=>{const date=new Date(d);if(Number.isNaN(date.getTime()))return d;const now=new Date();return date.toDateString()===now.toDateString()?date.toLocaleTimeString('az-AZ',{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('az-AZ',{day:'2-digit',month:'short'});};
const addressText=(a:Address[])=>a.map(x=>x.name?`${x.name} <${x.address}>`:x.address).join(', ');
const firstAddress=(a:Address[])=>a[0]?.name||a[0]?.address||'Naməlum göndərən';
const bytes=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${Math.round(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`;

export default function MailClient(){
 const [folder,setFolder]=useState('inbox'); const [messages,setMessages]=useState<Message[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [page,setPage]=useState(1); const [totalPages,setTotalPages]=useState(1); const [unread,setUnread]=useState(0); const [loading,setLoading]=useState(true); const [detailLoading,setDetailLoading]=useState(false); const [query,setQuery]=useState(''); const [search,setSearch]=useState(''); const [lastSync,setLastSync]=useState<string|null>(null); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [compose,setCompose]=useState(false); const [draftId,setDraftId]=useState<string|null>(null); const [clients,setClients]=useState<Client[]>([]); const [composeTo,setComposeTo]=useState(''); const [composeCc,setComposeCc]=useState(''); const [composeBcc,setComposeBcc]=useState(''); const [composeSubject,setComposeSubject]=useState(''); const [composeBody,setComposeBody]=useState(''); const [composeClient,setComposeClient]=useState(''); const [composeFiles,setComposeFiles]=useState<File[]>([]); const [saving,setSaving]=useState(false); const [composeInReplyTo,setComposeInReplyTo]=useState(''); const [composeReferences,setComposeReferences]=useState(''); const [forwardSource,setForwardSource]=useState<{uid:number;folder:string}|null>(null); const [mobilePanel,setMobilePanel]=useState<'list'|'viewer'>('list');

 const load=useCallback(async(f=folder,p=page,q=query)=>{setLoading(true);setError('');try{const r=await fetch(`/api/admin/mail/inbox?folder=${encodeURIComponent(f)}&page=${p}&q=${encodeURIComponent(q)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Mail qutusu yüklənmədi.');setMessages(d.messages||[]);setTotalPages(d.totalPages||1);setUnread(d.unreadCount||0);setLastSync(new Date().toISOString());}catch(e:any){setError(e.message||'Mail qutusu yüklənmədi.');}finally{setLoading(false);}},[folder,page,query]);
 useEffect(()=>{load(folder,page,query)},[folder,page,load]);
 useEffect(()=>{fetch('/api/admin/mail/clients',{cache:'no-store'}).then(r=>r.json()).then(d=>setClients(d.clients||[])).catch(()=>undefined);},[]);
 useEffect(()=>{const timer=setInterval(()=>load(folder,page,query),60000);return()=>clearInterval(timer)},[folder,page,query,load]);
 useEffect(()=>{const clientId=new URLSearchParams(window.location.search).get('clientId');if(clientId){const c=clients.find(x=>x.id===clientId);if(c){openCompose({clientId:c.id,to:c.email||''});}}},[clients]);

 async function openMessage(m:Message){if(folder==='drafts'&&m.draftId){const r=await fetch(`/api/admin/mail/draft?id=${m.draftId}`);const d=await r.json();if(r.ok){const x=d.draft as Draft;setDraftId(x.id);setComposeTo(x.to||'');setComposeCc(x.cc||'');setComposeBcc(x.bcc||'');setComposeSubject(x.subject||'');setComposeBody(x.body||'');setComposeClient(x.clientId||'');setCompose(true);}return;}setSelected(null);setMobilePanel('viewer');setDetailLoading(true);try{const sourceFolder=m.folder||folder;const r=await fetch(`/api/admin/mail/${m.uid}?folder=${encodeURIComponent(sourceFolder)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Email açıla bilmədi.');setSelected(d);setMessages(v=>v.map(x=>String(x.uid)===String(m.uid)?{...x,unread:false}:x));setUnread(v=>Math.max(0,v-1));}catch(e:any){setError(e.message)}finally{setDetailLoading(false);}}
 async function action(action:string,value?:boolean){if(!selected)return;const r=await fetch(`/api/admin/mail/${selected.uid}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder:selected.folder||folder,action,value})});const d=await r.json();if(!r.ok){setError(d.error||'Əməliyyat alınmadı.');return;}setNotice(action==='delete'?'Email silindi':action==='star'?(value?'Seçilmişlərə əlavə edildi':'Seçilmişlərdən çıxarıldı'):'Email oxunmamış kimi işarələndi');if(action==='delete'){setSelected(null);setMobilePanel('list');load(folder,page,query);}else if(action==='star')setSelected(x=>x?{...x,starred:Boolean(value)}:x);else setSelected(x=>x?{...x,unread:true}:x);}
 function openCompose(opts?:{clientId?:string;to?:string;subject?:string;body?:string;inReplyTo?:string;references?:string;forwardSource?:{uid:number;folder:string}}){setDraftId(null);setComposeInReplyTo(opts?.inReplyTo||'');setComposeReferences(opts?.references||'');setForwardSource(opts?.forwardSource||null);setComposeTo(opts?.to||'');setComposeCc('');setComposeBcc('');setComposeSubject(opts?.subject||'');setComposeBody(opts?.body||'');setComposeClient(opts?.clientId||'');setComposeFiles([]);setCompose(true);}
 function reply(kind:'reply'|'all'|'forward'){if(!selected)return;const to=kind==='forward'?'':kind==='all'?addressText(selected.from)+'; '+addressText(selected.to):addressText(selected.from);const prefix=kind==='forward'?'Fwd: ':'Re: ';const subject=selected.subject.toLowerCase().startsWith(prefix.toLowerCase())?selected.subject:`${prefix}${selected.subject}`;const quoted=`\n\n\n--- Original message ---\nFrom: ${addressText(selected.from)}\nDate: ${new Date(selected.date).toLocaleString('az-AZ')}\nSubject: ${selected.subject}\n\n${selected.text||''}`;openCompose({to,subject,body:quoted,inReplyTo:kind==='forward'?'':selected.messageId||'',references:kind==='forward'?'':[selected.references,selected.messageId].filter(Boolean).join(' '),forwardSource:kind==='forward'?{uid:Number(selected.uid),folder:selected.folder||folder}:undefined});}
 async function saveDraft(){setSaving(true);try{const f=new FormData();if(draftId)f.append('id',draftId);f.append('to',composeTo);f.append('cc',composeCc);f.append('bcc',composeBcc);f.append('subject',composeSubject);f.append('body',composeBody);f.append('clientId',composeClient);if(composeInReplyTo)f.append('inReplyTo',composeInReplyTo);if(composeReferences)f.append('references',composeReferences);if(forwardSource){f.append('forwardUid',String(forwardSource.uid));f.append('forwardFolder',forwardSource.folder);}composeFiles.forEach(x=>f.append('attachment',x));const r=await fetch('/api/admin/mail/draft',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||'Qaralama yadda saxlanmadı.');setDraftId(d.draft.id);setNotice('Qaralama yadda saxlanıldı');}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function send(){setSaving(true);try{const f=new FormData();if(draftId)f.append('draftId',draftId);f.append('to',composeTo);f.append('cc',composeCc);f.append('bcc',composeBcc);f.append('subject',composeSubject);f.append('text',composeBody);f.append('html',`<div>${composeBody.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>')}</div>`);f.append('clientId',composeClient);if(composeInReplyTo)f.append('inReplyTo',composeInReplyTo);if(composeReferences)f.append('references',composeReferences);if(forwardSource){f.append('forwardUid',String(forwardSource.uid));f.append('forwardFolder',forwardSource.folder);}composeFiles.forEach(x=>f.append('attachment',x));const r=await fetch('/api/admin/mail/send',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||'Email göndərilmədi.');setCompose(false);setDraftId(null);setNotice('Email uğurla göndərildi.');setFolder('sent');setPage(1);await load('sent',1,'');}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function refresh(){setSaving(true);try{const r=await fetch('/api/admin/mail/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder,page,q:query})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Mail qutusu yenilənmədi.');setMessages(d.messages||[]);setUnread(d.unreadCount||0);setTotalPages(d.totalPages||1);setLastSync(d.syncedAt);setNotice('Mail qutusu yeniləndi');}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 function chooseFolder(f:string){setFolder(f);setPage(1);setSelected(null);setMobilePanel('list');setQuery('');setSearch('');}
 const currentLabel=folders.find(x=>x[0]===folder)?.[1]||'Mail';
 return <main className="mailPage"><header className="mailTop"><div className="mailBrand"><a href="/admin" className="mailBack"><ArrowLeft size={16}/></a><div><span>NEW ERA</span><b>Mail Control</b></div></div><div className="mailTopActions"><span className="mailSync"><Clock3 size={13}/> {lastSync?`Son sinxronizasiya: ${new Date(lastSync).toLocaleTimeString('az-AZ',{hour:'2-digit',minute:'2-digit'})}`:'Sinxronizasiya gözlənilir'}</span><button onClick={refresh} disabled={saving}><RefreshCw size={15} className={saving?'spin':''}/> Yenilə</button><button className="mailComposeTop" onClick={()=>openCompose()}><PenLine size={15}/> Yeni məktub</button></div></header>
 <section className="mailShell"><aside className="mailSidebar"><button className="mailComposeButton" onClick={()=>openCompose()}><PenLine size={16}/> Yeni məktub</button>{folders.map(([key,label,Icon])=><button key={key} className={`mailFolder ${folder===key?'active':''}`} onClick={()=>chooseFolder(key)}><Icon size={16}/><span>{label}</span>{key==='inbox'&&unread>0?<em>{unread}</em>:key==='drafts'&&messages.length>0?<em>{messages.length}</em>:null}</button>)}<div className="mailSideHint"><MailIcon size={17}/><b>Şirkət poçtu</b><span>IMAP + SMTP · server-side</span></div></aside>
 <div className={`mailListPane ${mobilePanel==='viewer'?'mobileHidden':''}`}><div className="mailListHead"><div><small>NEW ERA MAIL</small><h1>{currentLabel}</h1></div><div className="mailListTools"><div className="mailSearch"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){setPage(1);setQuery(search.trim())}}} placeholder="Göndərən, mövzu, mətn..."/><kbd>Enter</kbd></div><button onClick={()=>{setPage(1);setQuery(search.trim())}} aria-label="Axtar"><Search size={15}/></button></div></div>{error&&<div className="mailAlert error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}{notice&&<div className="mailAlert success">{notice}<button onClick={()=>setNotice('')}><X size={13}/></button></div>}{loading?<div className="mailSkeleton">{Array.from({length:7}).map((_,i)=><div key={i}><i/><span/><span/></div>)}</div>:messages.length===0?<div className="mailEmpty"><MailIcon size={32}/><h3>{query?'Axtarış nəticəsi tapılmadı.':folder==='inbox'?'Gələn qutusu boşdur.':folder==='sent'?'Hələ göndərilmiş email yoxdur.':folder==='drafts'?'Yadda saxlanılmış qaralama yoxdur.':'Burada email yoxdur.'}</h3><p>{query?'Axtarış sözünü dəyişin.':'Yeni məktub göndərmək üçün yuxarıdakı düymədən istifadə edin.'}</p></div>:<div className="mailRows">{messages.map(m=><button key={`${m.folder||folder}-${m.uid}`} className={`mailRow ${m.unread?'unread':''} ${selected&&String(selected.uid)===String(m.uid)?'selected':''}`} onClick={()=>openMessage(m)}><span className="mailRowStar">{m.starred?<Star size={14} fill="currentColor"/>:<Star size={14}/>}</span><span className="mailRowMain"><strong>{firstAddress(m.from)}</strong><b>{m.subject}</b><small>{m.preview||''}</small></span><span className="mailRowDate">{fmtDate(m.date)}</span>{m.size&&m.size>0?<Paperclip size={13} className="mailRowAttach"/>:null}</button>)}</div>}
 <div className="mailPagination"><span>{messages.length} email</span><div><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}><ArrowLeft size={14}/></button><b>{page} / {totalPages}</b><button disabled={page>=totalPages} onClick={()=>setPage(x=>x+1)}><ArrowRight size={14}/></button></div></div></div>
 <section className={`mailViewer ${mobilePanel==='list'?'mobileHidden':''}`}>{detailLoading?<div className="mailViewerLoading"><div/><div/><div/><div/></div>:!selected?<div className="mailViewerEmpty"><MailIcon size={38}/><h2>Email seçin</h2><p>Oxumaq üçün soldakı siyahıdan bir məktub seçin.</p></div>:<><div className="mailViewerHead"><button className="mailMobileBack" onClick={()=>setMobilePanel('list')}><ArrowLeft size={16}/> Geri</button><div><small>{selected.clientName?`CRM · ${selected.clientName}`:'EMAIL'}</small><h2>{selected.subject}</h2></div><div className="mailViewerActions"><button onClick={()=>action('star',!selected.starred)} title="Seçilmiş"><Star size={16} fill={selected.starred?'currentColor':'none'}/></button><button onClick={()=>action('unread')} title="Oxunmamış"><MailIcon size={16}/></button><button onClick={()=>action('delete')} title="Sil"><Trash2 size={16}/></button></div></div><div className="mailMeta"><div className="mailAvatar">{firstAddress(selected.from).slice(0,1).toUpperCase()}</div><div><strong>{addressText(selected.from)}</strong><span>Kimə: {addressText(selected.to)||'—'}</span>{selected.cc.length>0&&<span>Surət: {addressText(selected.cc)}</span>}</div><time>{new Date(selected.date).toLocaleString('az-AZ')}</time></div><div className="mailBody">{selected.html?<div dangerouslySetInnerHTML={{__html:selected.html}}/>:<pre>{selected.text}</pre>}</div>{selected.attachments.length>0&&<div className="mailAttachments"><small>FAYLLAR · {selected.attachments.length}</small>{selected.attachments.map(a=><a key={a.filename} href={`/api/admin/mail/${selected.uid}/attachment?folder=${encodeURIComponent(selected.folder||folder)}&filename=${encodeURIComponent(a.filename)}`}><File size={15}/><span><b>{a.filename}</b><small>{bytes(a.size)} · {a.mimeType}</small></span><Download size={14}/></a>)}</div>}<div className="mailReplyBar"><button onClick={()=>reply('reply')}><Reply size={15}/> Cavabla</button><button onClick={()=>reply('all')}><Reply size={15}/> Hamısına cavabla</button><button onClick={()=>reply('forward')}><Forward size={15}/> Yönləndir</button></div></>}</section></section>
 {compose&&<div className="mailModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCompose(false)}}><section className="mailCompose"><header><div><small>NEW ERA MAIL</small><h2>Yeni məktub</h2></div><button onClick={()=>setCompose(false)}><X size={18}/></button></header><div className="mailComposeGrid"><label>Kimə<input value={composeTo} onChange={e=>setComposeTo(e.target.value)} placeholder="name@company.az"/></label><label>Surət<input value={composeCc} onChange={e=>setComposeCc(e.target.value)} placeholder="opsional"/></label><label>Gizli surət<input value={composeBcc} onChange={e=>setComposeBcc(e.target.value)} placeholder="opsional"/></label><label>Müştəri ilə əlaqələndir<select value={composeClient} onChange={e=>{setComposeClient(e.target.value);const c=clients.find(x=>x.id===e.target.value);if(c&&!composeTo)setComposeTo(c.email||'')}}><option value="">Müştəri seçin</option>{clients.map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}{c.company?` · ${c.company}`:''}</option>)}</select></label></div><label className="mailComposeSubject">Mövzu<input value={composeSubject} onChange={e=>setComposeSubject(e.target.value)} placeholder="Məktub mövzusu"/></label><textarea className="mailComposeBody" value={composeBody} onChange={e=>setComposeBody(e.target.value)} placeholder="Məktubunuzu yazın..."/><div className="mailComposeFiles"><label><Paperclip size={15}/> Fayl əlavə et<input type="file" multiple onChange={e=>setComposeFiles(Array.from(e.target.files||[]))}/></label>{composeFiles.map(f=><span key={`${f.name}-${f.size}`}>{f.name} · {bytes(f.size)}<button onClick={()=>setComposeFiles(v=>v.filter(x=>x!==f))}><X size={12}/></button></span>)}</div><footer><button className="ghost" onClick={()=>setCompose(false)}>Ləğv et</button><button className="ghost" onClick={saveDraft} disabled={saving}>Yadda saxla</button><button className="sendButton" onClick={send} disabled={saving}><Send size={14}/> {saving?'Göndərilir...':'Göndər'}</button></footer></section></div>}
 </main>;
}
