'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, LoaderCircle, Search, Sparkles } from 'lucide-react';
import '../marketing.css';

const targets=[['COMPANY','Company'],['DOCTOR','Doctor'],['CLINIC','Clinic'],['BEAUTY_SALON','Beauty Salon'],['BEAUTY_CENTER','Beauty Center'],['RESTAURANT','Restaurant'],['HOTEL','Hotel'],['FASHION_BRAND','Fashion Brand'],['RETAIL','Retail'],['EVENT_COMPANY','Event Company'],['MARKETING_AGENCY','Marketing Agency'],['OTHER','Other']];
const required=['name','contact','website','email','phone','instagram','facebook','linkedin','address','category'];
const labels:Record<string,string>={name:'Company / Person Name',contact:'Contact Person',website:'Website',email:'Email',phone:'Phone',instagram:'Instagram',facebook:'Facebook',linkedin:'LinkedIn',address:'Address',category:'Category'};
const filters=[['hasWebsite','Has website'],['noWebsite','No website'],['weakWebsite','Weak / outdated website'],['activeInstagram','Active Instagram'],['activeFacebook','Active Facebook'],['activeLinkedIn','Active LinkedIn'],['publicEmail','Public email available'],['publicPhone','Public phone available']];

export default function LeadSearchPage(){
 const [target,setTarget]=useState('COMPANY'); const [location,setLocation]=useState('Baku'); const [description,setDescription]=useState('Find businesses that may need website development, social media management or branding.'); const [count,setCount]=useState('25'); const [fields,setFields]=useState(['name','website','email','phone','category']); const [selectedFilters,setSelectedFilters]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [search,setSearch]=useState<any>(null);
 const toggle=(list:string[],value:string,set:(v:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 async function start(){setBusy(true);setError('');try{const r=await fetch('/api/admin/marketing/searches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:target,location,description,requestedCount:Number(count),requiredFields:fields,filters:selectedFilters})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSearch(d.search); const run=await fetch(`/api/admin/marketing/searches/${d.search.id}/run`,{method:'POST'}); const rd=await run.json(); if(!run.ok)throw new Error(rd.error); setSearch(rd.search);}catch(e:any){setError(e.message||'Research failed.')}finally{setBusy(false)}}
 useEffect(()=>{if(!search||!['RUNNING','QUEUED'].includes(search.status))return;const t=setInterval(async()=>{const r=await fetch(`/api/admin/marketing/searches/${search.id}`,{cache:'no-store'});const d=await r.json();if(r.ok)setSearch(d.search);},2500);return()=>clearInterval(t)},[search]);
 return <main className="marketingPage"><div className="marketingShell"><header className="marketingHeader"><div><span className="marketingKicker">AI LEAD RESEARCH</span><h1>Build a research brief.</h1><p>Search public business information and turn it into structured New Era leads.</p></div><Link href="/admin/marketing" className="marketingBack"><ArrowLeft size={14}/> Marketing</Link></header>
 <section className="searchLayout"><div className="searchFormCard"><div className="sectionTitle"><div><small>01 · TARGET</small><h2>Who are we looking for?</h2></div><Search size={18}/></div><label>Target type<select value={target} onChange={e=>setTarget(e.target.value)}>{targets.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Baku, Azerbaijan"/></label><label>Search description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5}/></label><label>Number of leads<select value={count} onChange={e=>setCount(e.target.value)}>{['10','25','50','100','250'].map(v=><option key={v}>{v}</option>)}</select></label>
 <div className="checkGroup"><small>REQUIRED INFORMATION</small>{required.map(k=><label key={k} className="checkRow"><input type="checkbox" checked={fields.includes(k)} onChange={()=>toggle(fields,k,setFields)}/><span>{labels[k]}</span></label>)}</div>
 <div className="checkGroup"><small>OPTIONAL FILTERS</small>{filters.map(([k,l])=><label key={k} className="checkRow"><input type="checkbox" checked={selectedFilters.includes(k)} onChange={()=>toggle(selectedFilters,k,setSelectedFilters)}/><span>{l}</span></label>)}</div>
 {error&&<div className="marketingError">{error}</div>}<button className="marketingPrimary wide" disabled={busy} onClick={start}>{busy?<><LoaderCircle className="spin" size={16}/> Research running…</>:<><Sparkles size={16}/> Start AI research <ArrowRight size={16}/></>}</button></div>
 <aside className="searchStatusCard"><div className="sectionTitle"><div><small>02 · LIVE JOB</small><h2>Research status</h2></div></div>{!search?<div className="emptyState"><Sparkles size={28}/><strong>Ready when you are.</strong><span>The provider and Claude pipeline will run server-side after you start the research.</span></div>:<div className="job"><div className="jobRing">{search.progress||0}%</div><strong>{search.status}</strong><div className="progress"><i style={{width:`${search.progress||0}%`}}/></div><div className="jobStats"><span><b>{search.sourcesScanned||0}</b> Sources scanned</span><span><b>{search.businessesFound||0}</b> Businesses found</span><span><b>{search.potentialLeads||0}</b> Potential leads</span><span><b>{search.duplicatesRemoved||0}</b> Duplicates removed</span><span><b>{search.verifiedLeads||0}</b> Verified leads</span></div>{search.status==='COMPLETED'&&<Link className="marketingPrimary" href="/admin/marketing/leads">View leads <ArrowRight size={16}/></Link>}{search.status==='FAILED'&&<div className="marketingError">{search.error}</div>}</div>}</aside></section>
 </div></main>
}
