'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Building2, UserRound } from 'lucide-react';
const jobs=['CEO / Founder','Marketing Manager','Brand Manager','SMM Manager','Creative Director','HR Manager','Sales Manager','Product Manager','Other'];
const industries=['Advertising & Creative','Technology','Retail & E-commerce','Healthcare','Finance','Real Estate','Education','Hospitality','Other'];
const sizes=['1–10','11–50','51–200','201–500','500+'];
export default function Register(){
 const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',password:'',company:'',website:'',jobTitle:'',industry:'',size:'',country:'Azerbaijan'}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,companySize:form.size})});const data=await res.json();if(!res.ok){setError(data.error||'Unable to create the account.');return;}if(data.user?.client)localStorage.setItem('new-era-client-session',JSON.stringify(data.user.client));window.location.href='/account';}catch{setError('Unable to connect to New Era right now.');}finally{setLoading(false);}}
 return <main className="authPage"><div className="authGlow"/><div className="authCard authWide"><Link className="authBrand" href="/"><img src="/new-era-logo.svg" alt="New Era"/></Link><div className="eyebrow">JOIN NEW ERA</div><h1>Create your <span>client account.</span></h1><p className="authIntro">Your company profile connects every brief, project and New Era conversation to one workspace.</p><form onSubmit={submit} className="authForm"><div className="authSectionTitle"><UserRound size={16}/><span>Personal details</span></div><div className="formSplit"><label>First name<input required value={form.firstName} onChange={e=>update('firstName',e.target.value)} placeholder="Your first name"/></label><label>Last name<input required value={form.lastName} onChange={e=>update('lastName',e.target.value)} placeholder="Your last name"/></label></div><div className="formSplit"><label>Work email<input required type="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="name@company.com"/></label><label>Phone<input required value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="+994 ..."/></label></div><label>Password<input required minLength={6} type="password" value={form.password} onChange={e=>update('password',e.target.value)} placeholder="At least 6 characters"/></label><div className="authSectionTitle"><Building2 size={16}/><span>Company profile</span></div><label>Company name<input required value={form.company} onChange={e=>update('company',e.target.value)} placeholder="Your company"/></label><div className="formSplit"><label>Your position<select required value={form.jobTitle} onChange={e=>update('jobTitle',e.target.value)}><option value="">Select your role</option>{jobs.map(x=><option key={x}>{x}</option>)}</select></label><label>Industry<select required value={form.industry} onChange={e=>update('industry',e.target.value)}><option value="">Select industry</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="formSplit"><label>Company size<select required value={form.size} onChange={e=>update('size',e.target.value)}><option value="">Select size</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Website <span className="optional">optional</span><input value={form.website} onChange={e=>update('website',e.target.value)} placeholder="company.com"/></label></div><label>Country<input value={form.country} onChange={e=>update('country',e.target.value)} placeholder="Azerbaijan"/></label>{error&&<div className="authError">{error}</div>}<button disabled={loading} className="primary authSubmit" type="submit">{loading?'Creating account…':'Create client account'} {!loading&&<ArrowRight size={16}/>}</button><div className="authFoot">Already have an account? <Link href="/login">Log in</Link></div></form><div className="authPrivacy">New Era keeps creator contact details private and manages client communication inside the platform.</div></div></main>;
}
